# Site settings
title: "On Software Engineering"
author: "Nguyen Phuong Que"
description: "This is a blog about software, some mathematics - Things I've learned and created."
keywords: "Software Engineering, Mathematics, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability"
biography: "..."
colophon: "© MMXIII — MMXVI by Hugo Sereno Ferreira.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://hugosereno.eu"

twitter_username: ferreira_hugo
github_username: hugoferreira
linkedin_username: hugoserenoferreira
facebook_username: hugo.sereno.ferreira
google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/


baseurl: ""
url: "jasmineque.github.io"

github_username: jasmineque
linkedin_username: 
facebook_username: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
