# Site settings
title: "On Software Engineering"
author: "Nguyen Phuong Que"
description: "This is a blog about software, some mathematics - Things I've learned and created."
keywords: "Software Engineering, Mathematics, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability"
biography: "..."
colophon: "This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""

github_username: jasmineque
linkedin_username: 
facebook_username: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
